[package]
name = "meetup"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.44.0", features = ["rt-multi-thread"] }
reqwest = "0.12.12"
axum = "0.8.1"
serde = {  version = "1.0.219", features = ["derive"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
